[rospy.client][INFO] 2015-05-22 14:03:53,941: init_node, name[/action_manager], pid[6813]
[xmlrpc][INFO] 2015-05-22 14:03:53,943: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2015-05-22 14:03:53,943: Started XML-RPC server [http://192.168.1.6:46338/]
[rospy.impl.masterslave][INFO] 2015-05-22 14:03:53,943: _ready: http://192.168.1.6:46338/
[xmlrpc][INFO] 2015-05-22 14:03:53,943: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2015-05-22 14:03:53,944: Registering with master node http://localhost:11311
[rospy.init][INFO] 2015-05-22 14:03:53,945: ROS Slave URI: [http://192.168.1.6:46338/]
[rospy.init][INFO] 2015-05-22 14:03:53,945: registered with master
[rospy.rosout][INFO] 2015-05-22 14:03:53,945: initializing /rosout core topic
[rospy.rosout][INFO] 2015-05-22 14:03:53,948: connected to core topic /rosout
[rospy.simtime][INFO] 2015-05-22 14:03:53,952: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2015-05-22 14:03:54,478: I will subscribe to the topic current_emotion
[rospy.internal][INFO] 2015-05-22 14:03:54,484: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2015-05-22 14:03:54,569: topic[/activity] adding connection to [http://192.168.1.6:53512/], count 0
[rospy.internal][INFO] 2015-05-22 14:03:54,571: topic[/activity] adding connection to [http://192.168.1.6:48332/], count 1
[rospy.internal][INFO] 2015-05-22 14:03:54,574: topic[/state_activity] adding connection to [http://192.168.1.6:47738/], count 0
[rospy.internal][INFO] 2015-05-22 14:03:54,574: topic[/current_emotion] adding connection to [http://192.168.1.6:38303/], count 0
[rospy.internal][INFO] 2015-05-22 14:03:54,638: topic[/activity] adding connection to [http://192.168.1.6:44378/], count 2
[rospy.internal][INFO] 2015-05-22 14:03:54,646: topic[/activity] adding connection to [http://192.168.1.8:48823/], count 3
[rospy.internal][INFO] 2015-05-22 14:03:54,679: topic[/activity] adding connection to [http://192.168.1.8:48823/], count 4
[rospy.internal][INFO] 2015-05-22 14:03:54,680: topic[/activity] removing connection to http://192.168.1.8:48823/
[rospy.internal][WARNING] 2015-05-22 14:03:54,680: Unknown error initiating TCP/IP socket to 192.168.1.8:54895 (http://192.168.1.8:48823/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][WARNING] 2015-05-22 14:26:50,793: Unknown error initiating TCP/IP socket to 192.168.1.6:34509 (http://192.168.1.6:48332/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2015-05-22 14:26:50,793: topic[/activity] removing connection to http://192.168.1.6:48332/
[rospy.internal][INFO] 2015-05-22 14:28:04,427: topic[/stop_learning] adding connection to [http://192.168.1.6:37776/], count 0
[rospy.internal][ERROR] 2015-05-22 14:28:04,447: Unable to initiate TCP/IP socket to 192.168.1.6:53152 (http://192.168.1.6:44378/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2015-05-22 14:28:05,449: Unknown error initiating TCP/IP socket to 192.168.1.6:53152 (http://192.168.1.6:44378/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 14:28:05,449: topic[/activity] removing connection to http://192.168.1.6:44378/
[rospy.internal][ERROR] 2015-05-22 14:28:08,372: Unable to initiate TCP/IP socket to 192.168.1.6:58278 (http://192.168.1.6:47738/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2015-05-22 14:28:08,471: signal_shutdown [Interaction exited]
[rospy.internal][INFO] 2015-05-22 14:28:08,478: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2015-05-22 14:28:08,478: topic[/state_activity] removing connection to http://192.168.1.6:47738/
[rospy.internal][INFO] 2015-05-22 14:28:08,479: topic[/current_emotion] removing connection to http://192.168.1.6:38303/
[rospy.internal][INFO] 2015-05-22 14:28:08,479: topic[/activity] removing connection to http://192.168.1.6:53512/
[rospy.internal][INFO] 2015-05-22 14:28:08,479: topic[/activity] removing connection to http://192.168.1.8:48823/
[rospy.internal][INFO] 2015-05-22 14:28:08,479: topic[/stop_learning] removing connection to http://192.168.1.6:37776/
[rospy.impl.masterslave][INFO] 2015-05-22 14:28:08,479: Interaction exited
[rospy.core][INFO] 2015-05-22 14:28:08,917: signal_shutdown [atexit]
[rospy.client][INFO] 2015-05-22 14:28:32,246: init_node, name[/action_manager], pid[1340]
[xmlrpc][INFO] 2015-05-22 14:28:32,246: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2015-05-22 14:28:32,247: Started XML-RPC server [http://192.168.1.6:52757/]
[rospy.impl.masterslave][INFO] 2015-05-22 14:28:32,247: _ready: http://192.168.1.6:52757/
[rospy.init][INFO] 2015-05-22 14:28:32,249: ROS Slave URI: [http://192.168.1.6:52757/]
[xmlrpc][INFO] 2015-05-22 14:28:32,249: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2015-05-22 14:28:32,250: Registering with master node http://localhost:11311
[rospy.init][INFO] 2015-05-22 14:28:32,350: registered with master
[rospy.rosout][INFO] 2015-05-22 14:28:32,350: initializing /rosout core topic
[rospy.rosout][INFO] 2015-05-22 14:28:32,353: connected to core topic /rosout
[rospy.simtime][INFO] 2015-05-22 14:28:32,354: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2015-05-22 14:28:32,844: I will subscribe to the topic current_emotion
[rospy.internal][INFO] 2015-05-22 14:28:32,851: topic[/current_emotion] adding connection to [http://192.168.1.6:36311/], count 0
[rospy.internal][INFO] 2015-05-22 14:28:32,856: topic[/state_activity] adding connection to [http://192.168.1.6:43435/], count 0
[rospy.internal][INFO] 2015-05-22 14:28:32,927: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2015-05-22 14:28:32,930: topic[/activity] adding connection to [http://192.168.1.6:41420/], count 0
[rospy.internal][INFO] 2015-05-22 14:28:32,931: topic[/activity] adding connection to [http://192.168.1.6:53593/], count 1
[rospy.internal][INFO] 2015-05-22 14:28:32,965: topic[/activity] adding connection to [http://192.168.1.8:48823/], count 2
[rospy.internal][INFO] 2015-05-22 14:28:32,998: topic[/activity] adding connection to [http://192.168.1.6:41437/], count 3
[rospy.internal][INFO] 2015-05-22 14:33:19,376: topic[/stop_learning] adding connection to [http://192.168.1.6:37710/], count 0
[rospy.internal][ERROR] 2015-05-22 14:33:19,395: Unable to initiate TCP/IP socket to 192.168.1.6:49898 (http://192.168.1.6:41437/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2015-05-22 14:33:20,397: Unknown error initiating TCP/IP socket to 192.168.1.6:49898 (http://192.168.1.6:41437/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 14:33:20,397: topic[/activity] removing connection to http://192.168.1.6:41437/
[rospy.internal][ERROR] 2015-05-22 14:33:23,306: Unable to initiate TCP/IP socket to 192.168.1.6:59638 (http://192.168.1.6:43435/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2015-05-22 14:33:23,448: signal_shutdown [Interaction exited]
[rospy.internal][INFO] 2015-05-22 14:33:23,459: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2015-05-22 14:33:23,460: topic[/state_activity] removing connection to http://192.168.1.6:43435/
[rospy.internal][INFO] 2015-05-22 14:33:23,460: topic[/current_emotion] removing connection to http://192.168.1.6:36311/
[rospy.internal][INFO] 2015-05-22 14:33:23,461: topic[/activity] removing connection to http://192.168.1.6:41420/
[rospy.internal][INFO] 2015-05-22 14:33:23,461: topic[/activity] removing connection to http://192.168.1.6:53593/
[rospy.internal][INFO] 2015-05-22 14:33:23,462: topic[/activity] removing connection to http://192.168.1.8:48823/
[rospy.internal][INFO] 2015-05-22 14:33:23,463: topic[/stop_learning] removing connection to http://192.168.1.6:37710/
[rospy.impl.masterslave][INFO] 2015-05-22 14:33:23,463: Interaction exited
[rospy.core][INFO] 2015-05-22 14:33:23,765: signal_shutdown [atexit]
[rospy.client][INFO] 2015-05-22 14:34:48,144: init_node, name[/action_manager], pid[15104]
[xmlrpc][INFO] 2015-05-22 14:34:48,145: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2015-05-22 14:34:48,146: Started XML-RPC server [http://192.168.1.6:50191/]
[rospy.impl.masterslave][INFO] 2015-05-22 14:34:48,146: _ready: http://192.168.1.6:50191/
[rospy.init][INFO] 2015-05-22 14:34:48,146: ROS Slave URI: [http://192.168.1.6:50191/]
[rospy.registration][INFO] 2015-05-22 14:34:48,147: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2015-05-22 14:34:48,147: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2015-05-22 14:34:48,248: registered with master
[rospy.rosout][INFO] 2015-05-22 14:34:48,248: initializing /rosout core topic
[rospy.rosout][INFO] 2015-05-22 14:34:48,254: connected to core topic /rosout
[rospy.simtime][INFO] 2015-05-22 14:34:48,256: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2015-05-22 14:34:48,816: topic[/rosout] adding connection to [/rosout], count 0
[rosout][INFO] 2015-05-22 14:34:48,848: I will subscribe to the topic current_emotion
[rospy.internal][INFO] 2015-05-22 14:34:49,013: topic[/activity] adding connection to [http://192.168.1.6:43278/], count 0
[rospy.internal][INFO] 2015-05-22 14:34:49,014: topic[/activity] adding connection to [http://192.168.1.6:37787/], count 1
[rospy.internal][INFO] 2015-05-22 14:34:49,015: topic[/current_emotion] adding connection to [http://192.168.1.6:34250/], count 0
[rospy.internal][INFO] 2015-05-22 14:34:49,015: topic[/state_activity] adding connection to [http://192.168.1.6:50075/], count 0
[rospy.internal][INFO] 2015-05-22 14:34:49,033: topic[/activity] adding connection to [http://192.168.1.6:48943/], count 2
[rospy.internal][INFO] 2015-05-22 14:34:49,121: topic[/activity] adding connection to [http://192.168.1.8:48823/], count 3
[rospy.internal][INFO] 2015-05-22 14:34:49,122: topic[/activity] adding connection to [http://192.168.1.8:48823/], count 4
[rospy.internal][INFO] 2015-05-22 14:34:49,122: topic[/activity] removing connection to http://192.168.1.8:48823/
[rospy.internal][WARNING] 2015-05-22 14:34:49,123: Unknown error initiating TCP/IP socket to 192.168.1.8:54895 (http://192.168.1.8:48823/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer

[rospy.internal][ERROR] 2015-05-22 14:40:53,112: Unable to initiate TCP/IP socket to 192.168.1.6:44420 (http://192.168.1.6:48943/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2015-05-22 14:40:53,119: topic[/stop_learning] adding connection to [http://192.168.1.6:39867/], count 0
[rospy.internal][WARNING] 2015-05-22 14:40:53,519: Unknown error initiating TCP/IP socket to 192.168.1.6:58338 (http://192.168.1.6:34250/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 14:40:53,520: topic[/current_emotion] removing connection to http://192.168.1.6:34250/
[rospy.internal][WARNING] 2015-05-22 14:40:54,113: Unknown error initiating TCP/IP socket to 192.168.1.6:44420 (http://192.168.1.6:48943/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2015-05-22 14:40:54,114: topic[/activity] removing connection to http://192.168.1.6:48943/
[rospy.internal][ERROR] 2015-05-22 14:40:57,540: Unable to initiate TCP/IP socket to 192.168.1.6:34125 (http://192.168.1.6:37787/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.core][INFO] 2015-05-22 14:40:57,542: signal_shutdown [Interaction exited]
[rospy.internal][INFO] 2015-05-22 14:40:57,548: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2015-05-22 14:40:57,548: topic[/state_activity] removing connection to http://192.168.1.6:50075/
[rospy.internal][INFO] 2015-05-22 14:40:57,548: topic[/activity] removing connection to http://192.168.1.6:43278/
[rospy.internal][INFO] 2015-05-22 14:40:57,548: topic[/activity] removing connection to http://192.168.1.6:37787/
[rospy.internal][INFO] 2015-05-22 14:40:57,548: topic[/activity] removing connection to http://192.168.1.8:48823/
[rospy.internal][WARNING] 2015-05-22 14:40:57,548: Unknown error initiating TCP/IP socket to 192.168.1.6:50657 (http://192.168.1.6:50075/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2015-05-22 14:40:57,549: topic[/stop_learning] removing connection to http://192.168.1.6:39867/
[rospy.impl.masterslave][INFO] 2015-05-22 14:40:57,549: Interaction exited
[rospy.core][INFO] 2015-05-22 14:40:57,847: signal_shutdown [atexit]
