[rospy.client][INFO] 2016-01-26 08:34:24,990: init_node, name[/activity_manager], pid[16920]
[xmlrpc][INFO] 2016-01-26 08:34:24,991: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-01-26 08:34:24,991: Started XML-RPC server [http://10.0.0.11:56334/]
[rospy.impl.masterslave][INFO] 2016-01-26 08:34:24,991: _ready: http://10.0.0.11:56334/
[rospy.init][INFO] 2016-01-26 08:34:24,994: ROS Slave URI: [http://10.0.0.11:56334/]
[rospy.registration][INFO] 2016-01-26 08:34:24,994: Registering with master node http://10.0.0.11:11311/
[xmlrpc][INFO] 2016-01-26 08:34:24,995: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2016-01-26 08:34:25,094: registered with master
[rospy.rosout][INFO] 2016-01-26 08:34:25,094: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-26 08:34:25,096: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-26 08:34:25,097: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-26 08:34:25,117: topic[/activity] adding connection to [http://10.0.0.11:56334/], count 0
[rosout][INFO] 2016-01-26 08:34:25,121: Starting new timer
[rosout][INFO] 2016-01-26 08:34:25,121: Waiting for display manager services to become available
[rospy.internal][INFO] 2016-01-26 08:34:25,122: topic[/activity] adding connection to [/activity_manager], count 0
[rospy.internal][INFO] 2016-01-26 08:34:25,165: topic[/watchdog_clear/tablet] adding connection to [http://10.0.0.4:46249/], count 0
[rospy.internal][INFO] 2016-01-26 08:34:25,208: topic[/activity] adding connection to [/log], count 1
[rospy.internal][INFO] 2016-01-26 08:34:25,267: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-26 08:34:26,260: topic[/activity] adding connection to [/drawing_nao], count 2
[rospy.internal][INFO] 2016-01-26 08:34:26,289: topic[/activity] adding connection to [http://10.0.0.11:45260/], count 1
[rospy.internal][INFO] 2016-01-26 08:34:26,379: topic[/activity] adding connection to [/learning_words_nao], count 3
[rosout][INFO] 2016-01-26 08:34:27,123: Nao configuration: writing=True, speaking=True (english), standing=False, handedness=right
[rosout][INFO] 2016-01-26 08:34:30,231: STATE: waiting_for_robot_to_connect
[rosout][INFO] 2016-01-26 08:34:30,732: STATE: STARTING_INTERACTION
[rosout][INFO] 2016-01-26 08:34:32,546: NAO: Hello. I'm Clem.
[rosout][INFO] 2016-01-26 08:34:34,048: STATE: ACTIVITY
[rosout][INFO] 2016-01-26 08:34:52,268: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 08:34:59,212: Re-connection
[rospy.internal][INFO] 2016-01-26 08:35:49,550: topic[/stop_learning] adding connection to [http://10.0.0.11:36339/], count 0
[rospy.internal][ERROR] 2016-01-26 08:35:50,370: Unable to initiate TCP/IP socket to 10.0.0.11:51826 (http://10.0.0.11:45260/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rosout][INFO] 2016-01-26 08:35:50,615: STATE: STOPPING
[rospy.internal][WARNING] 2016-01-26 08:35:51,371: Unknown error initiating TCP/IP socket to 10.0.0.11:51826 (http://10.0.0.11:45260/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-26 08:35:51,372: topic[/activity] removing connection to http://10.0.0.11:45260/
[rospy.internal][WARNING] 2016-01-26 08:35:52,479: Unknown error initiating TCP/IP socket to 10.0.0.11:44709 (http://10.0.0.11:36339/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-26 08:35:52,479: topic[/stop_learning] removing connection to http://10.0.0.11:36339/
[rospy.core][INFO] 2016-01-26 08:35:54,760: signal_shutdown [Interaction exited]
[rospy.internal][INFO] 2016-01-26 08:35:54,765: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-26 08:35:54,765: topic[/activity] removing connection to /activity_manager
[rospy.internal][INFO] 2016-01-26 08:35:54,766: topic[/activity] removing connection to /log
[rospy.internal][INFO] 2016-01-26 08:35:54,766: topic[/activity] removing connection to /drawing_nao
[rospy.internal][INFO] 2016-01-26 08:35:54,766: topic[/activity] removing connection to /learning_words_nao
[rospy.internal][INFO] 2016-01-26 08:35:54,767: topic[/activity] removing connection to http://10.0.0.11:56334/
[rospy.internal][INFO] 2016-01-26 08:35:54,767: topic[/watchdog_clear/tablet] removing connection to http://10.0.0.4:46249/
[rospy.internal][ERROR] 2016-01-26 08:35:54,767: Unable to initiate TCP/IP socket to 10.0.0.11:43767 (http://10.0.0.11:56334/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.impl.masterslave][INFO] 2016-01-26 08:35:54,768: Interaction exited
[rospy.internal][WARNING] 2016-01-26 08:35:54,775: Unknown error initiating TCP/IP socket to 10.0.0.4:51921 (http://10.0.0.4:46249/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rosout][INFO] 2016-01-26 08:35:54,883: Stopped
[rospy.core][INFO] 2016-01-26 08:35:54,884: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-26 08:40:41,861: init_node, name[/activity_manager], pid[22125]
[xmlrpc][INFO] 2016-01-26 08:40:41,861: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-26 08:40:41,862: ROS Slave URI: [http://10.0.0.11:58493/]
[xmlrpc][INFO] 2016-01-26 08:40:41,862: Started XML-RPC server [http://10.0.0.11:58493/]
[rospy.impl.masterslave][INFO] 2016-01-26 08:40:41,862: _ready: http://10.0.0.11:58493/
[xmlrpc][INFO] 2016-01-26 08:40:41,862: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-26 08:40:41,863: Registering with master node http://10.0.0.11:11311/
[rospy.init][INFO] 2016-01-26 08:40:41,962: registered with master
[rospy.rosout][INFO] 2016-01-26 08:40:41,962: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-26 08:40:41,965: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-26 08:40:41,966: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2016-01-26 08:40:42,038: topic[/activity] adding connection to [http://10.0.0.11:58493/], count 0
[rosout][INFO] 2016-01-26 08:40:42,039: Starting new timer
[rospy.internal][INFO] 2016-01-26 08:40:42,048: topic[/activity] adding connection to [/activity_manager], count 0
[rosout][INFO] 2016-01-26 08:40:42,051: Waiting for display manager services to become available
[rospy.internal][INFO] 2016-01-26 08:40:42,052: topic[/activity] adding connection to [/log], count 1
[rospy.internal][INFO] 2016-01-26 08:40:42,093: topic[/watchdog_clear/tablet] adding connection to [http://10.0.0.4:46249/], count 0
[rospy.internal][INFO] 2016-01-26 08:40:42,134: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-26 08:40:42,625: topic[/activity] adding connection to [/learning_words_nao], count 2
[rospy.internal][INFO] 2016-01-26 08:40:42,631: topic[/activity] adding connection to [/drawing_nao], count 3
[rospy.internal][INFO] 2016-01-26 08:40:42,665: topic[/activity] adding connection to [http://10.0.0.11:39519/], count 1
[rosout][INFO] 2016-01-26 08:40:44,054: Nao configuration: writing=True, speaking=True (english), standing=False, handedness=right
[rosout][INFO] 2016-01-26 08:40:47,283: STATE: waiting_for_robot_to_connect
[rosout][INFO] 2016-01-26 08:40:47,784: STATE: STARTING_INTERACTION
[rosout][INFO] 2016-01-26 08:40:49,426: NAO: Hello. I'm Clem.
[rosout][INFO] 2016-01-26 08:40:50,928: STATE: ACTIVITY
[rosout][INFO] 2016-01-26 08:41:10,470: Haven't received a clear on 'watchdog_clear/tablet' topic
[rospy.internal][INFO] 2016-01-26 08:41:34,260: topic[/stop_learning] adding connection to [http://10.0.0.11:50640/], count 0
[rospy.internal][ERROR] 2016-01-26 08:41:34,866: Unable to initiate TCP/IP socket to 10.0.0.11:51323 (http://10.0.0.11:39519/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2016-01-26 08:41:34,866: topic[/activity] adding connection to [/drawing_nao], count 4
[rospy.internal][INFO] 2016-01-26 08:41:34,867: topic[/activity] removing connection to /drawing_nao
[rospy.internal][WARNING] 2016-01-26 08:41:35,866: Unknown error initiating TCP/IP socket to 10.0.0.11:51323 (http://10.0.0.11:39519/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-26 08:41:35,866: topic[/activity] removing connection to http://10.0.0.11:39519/
[rosout][INFO] 2016-01-26 08:41:35,968: STATE: STOPPING
[rospy.internal][WARNING] 2016-01-26 08:41:37,198: Unknown error initiating TCP/IP socket to 10.0.0.11:52700 (http://10.0.0.11:50640/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-26 08:41:37,198: topic[/stop_learning] removing connection to http://10.0.0.11:50640/
[rospy.core][INFO] 2016-01-26 08:41:40,135: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-01-26 08:41:40,140: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-26 08:41:40,140: topic[/activity] removing connection to /activity_manager
[rospy.internal][INFO] 2016-01-26 08:41:40,141: topic[/activity] removing connection to /log
[rospy.internal][INFO] 2016-01-26 08:41:40,141: topic[/activity] removing connection to /learning_words_nao
[rospy.internal][INFO] 2016-01-26 08:41:40,141: topic[/activity] removing connection to /drawing_nao
[rospy.internal][ERROR] 2016-01-26 08:41:40,141: Unable to initiate TCP/IP socket to 10.0.0.11:47279 (http://10.0.0.11:58493/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2016-01-26 08:41:40,142: topic[/activity] removing connection to http://10.0.0.11:58493/
[rospy.internal][INFO] 2016-01-26 08:41:40,142: topic[/watchdog_clear/tablet] removing connection to http://10.0.0.4:46249/
[rospy.impl.masterslave][INFO] 2016-01-26 08:41:40,142: signal-2
[rospy.core][INFO] 2016-01-26 08:41:40,781: signal_shutdown [Interaction exited]
[rosout][INFO] 2016-01-26 08:41:40,781: Stopped
[rospy.core][INFO] 2016-01-26 08:41:40,782: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-26 08:41:51,418: init_node, name[/activity_manager], pid[23693]
[xmlrpc][INFO] 2016-01-26 08:41:51,419: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-26 08:41:51,419: ROS Slave URI: [http://10.0.0.11:39509/]
[xmlrpc][INFO] 2016-01-26 08:41:51,419: Started XML-RPC server [http://10.0.0.11:39509/]
[rospy.impl.masterslave][INFO] 2016-01-26 08:41:51,419: _ready: http://10.0.0.11:39509/
[xmlrpc][INFO] 2016-01-26 08:41:51,420: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-26 08:41:51,420: Registering with master node http://10.0.0.11:11311/
[rospy.init][INFO] 2016-01-26 08:41:51,519: registered with master
[rospy.rosout][INFO] 2016-01-26 08:41:51,520: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-26 08:41:51,521: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-26 08:41:51,523: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2016-01-26 08:41:51,543: Starting new timer
[rosout][INFO] 2016-01-26 08:41:51,543: Waiting for display manager services to become available
[rospy.internal][INFO] 2016-01-26 08:41:51,586: topic[/activity] adding connection to [http://10.0.0.11:39509/], count 0
[rospy.internal][INFO] 2016-01-26 08:41:51,588: topic[/activity] adding connection to [/activity_manager], count 0
[rospy.internal][INFO] 2016-01-26 08:41:51,600: topic[/watchdog_clear/tablet] adding connection to [http://10.0.0.4:46249/], count 0
[rospy.internal][INFO] 2016-01-26 08:41:51,608: topic[/activity] adding connection to [/log], count 1
[rospy.internal][INFO] 2016-01-26 08:41:51,758: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-26 08:41:52,537: topic[/activity] adding connection to [/learning_words_nao], count 2
[rospy.internal][INFO] 2016-01-26 08:41:52,553: topic[/activity] adding connection to [/drawing_nao], count 3
[rospy.internal][INFO] 2016-01-26 08:41:52,588: topic[/activity] adding connection to [http://10.0.0.11:51784/], count 1
[rosout][INFO] 2016-01-26 08:41:53,546: Nao configuration: writing=True, speaking=True (english), standing=False, handedness=right
[rosout][INFO] 2016-01-26 08:41:56,610: STATE: waiting_for_robot_to_connect
[rosout][INFO] 2016-01-26 08:41:57,111: STATE: STARTING_INTERACTION
[rosout][INFO] 2016-01-26 08:41:58,770: NAO: Hello. I'm Clem.
[rosout][INFO] 2016-01-26 08:42:00,272: STATE: ACTIVITY
[rosout][INFO] 2016-01-26 08:42:14,705: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 08:42:47,188: Re-connection
[rospy.internal][WARNING] 2016-01-26 08:42:49,293: Unknown error initiating TCP/IP socket to 10.0.0.4:51921 (http://10.0.0.4:46249/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2016-01-26 08:42:49,293: topic[/watchdog_clear/tablet] removing connection to http://10.0.0.4:46249/
[rosout][INFO] 2016-01-26 08:42:49,348: Haven't received a clear on 'watchdog_clear/tablet' topic
[rospy.internal][INFO] 2016-01-26 08:42:55,119: topic[/watchdog_clear/tablet] adding connection to [http://10.0.0.4:38576/], count 0
[rosout][INFO] 2016-01-26 08:42:55,219: Re-connection
[rospy.internal][INFO] 2016-01-26 08:43:27,273: topic[/stop_learning] adding connection to [http://10.0.0.11:43213/], count 0
[rospy.internal][ERROR] 2016-01-26 08:43:28,119: Unable to initiate TCP/IP socket to 10.0.0.11:39472 (http://10.0.0.11:51784/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rosout][WARNING] 2016-01-26 08:43:28,792: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2016-01-26 08:43:28,793: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2016-01-26 08:43:28,794: topic[/activity] adding connection to [/learning_words_nao], count 4
[rospy.internal][INFO] 2016-01-26 08:43:28,794: topic[/activity] removing connection to /learning_words_nao
[rosout][INFO] 2016-01-26 08:43:28,968: STATE: STOPPING
[rospy.internal][WARNING] 2016-01-26 08:43:29,121: Unknown error initiating TCP/IP socket to 10.0.0.11:39472 (http://10.0.0.11:51784/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-26 08:43:29,121: topic[/activity] removing connection to http://10.0.0.11:51784/
[rospy.internal][ERROR] 2016-01-26 08:43:30,235: Unable to initiate TCP/IP socket to 10.0.0.11:39091 (http://10.0.0.11:43213/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-26 08:43:31,235: Unknown error initiating TCP/IP socket to 10.0.0.11:39091 (http://10.0.0.11:43213/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-26 08:43:31,235: topic[/stop_learning] removing connection to http://10.0.0.11:43213/
[rospy.core][INFO] 2016-01-26 08:43:33,293: signal_shutdown [Interaction exited]
[rospy.internal][INFO] 2016-01-26 08:43:33,297: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-26 08:43:33,297: topic[/activity] removing connection to /activity_manager
[rospy.internal][INFO] 2016-01-26 08:43:33,297: topic[/activity] removing connection to /log
[rospy.internal][INFO] 2016-01-26 08:43:33,299: topic[/activity] removing connection to /drawing_nao
[rospy.internal][INFO] 2016-01-26 08:43:33,299: topic[/activity] removing connection to /learning_words_nao
[rospy.internal][INFO] 2016-01-26 08:43:33,299: topic[/activity] removing connection to http://10.0.0.11:39509/
[rospy.internal][INFO] 2016-01-26 08:43:33,299: topic[/watchdog_clear/tablet] removing connection to http://10.0.0.4:38576/
[rospy.impl.masterslave][INFO] 2016-01-26 08:43:33,300: Interaction exited
[rospy.internal][ERROR] 2016-01-26 08:43:33,301: Unable to initiate TCP/IP socket to 10.0.0.11:51648 (http://10.0.0.11:39509/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rosout][INFO] 2016-01-26 08:43:33,431: Stopped
[rospy.core][INFO] 2016-01-26 08:43:33,432: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-26 08:43:51,776: init_node, name[/activity_manager], pid[26555]
[xmlrpc][INFO] 2016-01-26 08:43:51,776: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-26 08:43:51,777: ROS Slave URI: [http://10.0.0.11:60148/]
[xmlrpc][INFO] 2016-01-26 08:43:51,777: Started XML-RPC server [http://10.0.0.11:60148/]
[rospy.impl.masterslave][INFO] 2016-01-26 08:43:51,777: _ready: http://10.0.0.11:60148/
[xmlrpc][INFO] 2016-01-26 08:43:51,777: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-26 08:43:51,777: Registering with master node http://10.0.0.11:11311/
[rospy.init][INFO] 2016-01-26 08:43:51,877: registered with master
[rospy.rosout][INFO] 2016-01-26 08:43:51,877: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-26 08:43:51,879: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-26 08:43:51,881: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2016-01-26 08:43:51,954: Starting new timer
[rosout][INFO] 2016-01-26 08:43:51,955: Waiting for display manager services to become available
[rospy.internal][INFO] 2016-01-26 08:43:52,007: topic[/activity] adding connection to [http://10.0.0.11:60148/], count 0
[rospy.internal][INFO] 2016-01-26 08:43:52,021: topic[/activity] adding connection to [/activity_manager], count 0
[rospy.internal][INFO] 2016-01-26 08:43:52,042: topic[/watchdog_clear/tablet] adding connection to [http://10.0.0.4:38576/], count 0
[rospy.internal][INFO] 2016-01-26 08:43:52,075: topic[/activity] adding connection to [/log], count 1
[rospy.internal][INFO] 2016-01-26 08:43:52,099: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-26 08:43:52,840: topic[/activity] adding connection to [/learning_words_nao], count 2
[rospy.internal][INFO] 2016-01-26 08:43:53,043: topic[/activity] adding connection to [/drawing_nao], count 3
[rospy.internal][INFO] 2016-01-26 08:43:53,069: topic[/activity] adding connection to [http://10.0.0.11:34275/], count 1
[rosout][INFO] 2016-01-26 08:43:53,955: Nao configuration: writing=True, speaking=True (english), standing=False, handedness=right
[rosout][INFO] 2016-01-26 08:43:57,871: STATE: waiting_for_robot_to_connect
[rosout][INFO] 2016-01-26 08:43:58,372: STATE: STARTING_INTERACTION
[rosout][INFO] 2016-01-26 08:44:00,197: NAO: Hello. I'm Clem.
[rosout][INFO] 2016-01-26 08:44:01,699: STATE: ACTIVITY
[rosout][INFO] 2016-01-26 08:44:12,927: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 08:44:15,221: Re-connection
[rosout][INFO] 2016-01-26 08:45:22,405: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 08:45:24,881: Re-connection
[rosout][INFO] 2016-01-26 08:46:16,738: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 08:46:19,123: Re-connection
[rosout][INFO] 2016-01-26 08:47:12,881: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 08:47:15,284: Re-connection
[rosout][INFO] 2016-01-26 08:48:24,629: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 08:48:27,072: Re-connection
[rosout][INFO] 2016-01-26 08:49:02,346: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 08:49:04,788: Re-connection
[rosout][INFO] 2016-01-26 08:49:54,199: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 08:49:56,609: Re-connection
[rosout][INFO] 2016-01-26 08:50:49,875: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 08:50:52,301: Re-connection
[rosout][INFO] 2016-01-26 08:51:48,477: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 08:51:50,847: Re-connection
[rosout][INFO] 2016-01-26 08:52:46,469: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 08:52:48,716: Re-connection
[rosout][INFO] 2016-01-26 08:53:39,910: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 08:53:42,280: Re-connection
[rosout][INFO] 2016-01-26 08:54:29,748: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 08:54:32,094: Re-connection
[rosout][INFO] 2016-01-26 08:55:08,189: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 08:55:10,559: Re-connection
[rosout][INFO] 2016-01-26 08:56:00,360: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 08:56:02,617: Re-connection
[rosout][INFO] 2016-01-26 08:56:41,087: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 08:56:42,803: Re-connection
[rosout][INFO] 2016-01-26 08:57:41,007: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 08:57:43,180: Re-connection
[rosout][INFO] 2016-01-26 08:58:34,228: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 08:58:36,549: Re-connection
[rosout][INFO] 2016-01-26 08:59:23,969: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 08:59:26,258: Re-connection
[rosout][INFO] 2016-01-26 09:00:09,148: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:00:11,308: Re-connection
[rosout][INFO] 2016-01-26 09:00:46,039: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:00:47,954: Re-connection
[rospy.internal][WARNING] 2016-01-26 09:01:18,438: Unknown error initiating TCP/IP socket to 10.0.0.4:39801 (http://10.0.0.4:38576/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-26 09:01:18,438: topic[/watchdog_clear/tablet] removing connection to http://10.0.0.4:38576/
[rosout][INFO] 2016-01-26 09:01:18,559: Haven't received a clear on 'watchdog_clear/tablet' topic
[rospy.internal][INFO] 2016-01-26 09:01:18,999: topic[/watchdog_clear/tablet] adding connection to [http://10.0.0.4:58821/], count 0
[rosout][INFO] 2016-01-26 09:01:19,149: Re-connection
[rosout][INFO] 2016-01-26 09:01:51,398: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:01:53,616: Re-connection
[rospy.internal][INFO] 2016-01-26 09:02:27,957: topic[/stop_learning] adding connection to [http://10.0.0.11:36144/], count 0
[rospy.internal][ERROR] 2016-01-26 09:02:29,194: Unable to initiate TCP/IP socket to 10.0.0.11:47484 (http://10.0.0.11:34275/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2016-01-26 09:02:29,195: topic[/activity] adding connection to [/drawing_nao], count 4
[rospy.internal][INFO] 2016-01-26 09:02:29,195: topic[/activity] removing connection to /drawing_nao
[rosout][INFO] 2016-01-26 09:02:29,428: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:02:29,968: STATE: STOPPING
[rospy.internal][WARNING] 2016-01-26 09:02:30,195: Unknown error initiating TCP/IP socket to 10.0.0.11:47484 (http://10.0.0.11:34275/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-26 09:02:30,195: topic[/activity] removing connection to http://10.0.0.11:34275/
[rospy.internal][ERROR] 2016-01-26 09:02:30,914: Unable to initiate TCP/IP socket to 10.0.0.11:35107 (http://10.0.0.11:36144/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rosout][INFO] 2016-01-26 09:02:31,668: Re-connection
[rospy.internal][WARNING] 2016-01-26 09:02:31,915: Unknown error initiating TCP/IP socket to 10.0.0.11:35107 (http://10.0.0.11:36144/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-26 09:02:31,915: topic[/stop_learning] removing connection to http://10.0.0.11:36144/
[rospy.core][INFO] 2016-01-26 09:02:34,068: signal_shutdown [Interaction exited]
[rospy.internal][INFO] 2016-01-26 09:02:34,074: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-26 09:02:34,074: topic[/activity] removing connection to /activity_manager
[rospy.internal][ERROR] 2016-01-26 09:02:34,076: Unable to initiate TCP/IP socket to 10.0.0.11:39187 (http://10.0.0.11:60148/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2016-01-26 09:02:34,076: topic[/activity] removing connection to /log
[rospy.internal][INFO] 2016-01-26 09:02:34,076: topic[/activity] removing connection to /learning_words_nao
[rospy.internal][INFO] 2016-01-26 09:02:34,076: topic[/activity] removing connection to /drawing_nao
[rospy.internal][INFO] 2016-01-26 09:02:34,076: topic[/activity] removing connection to http://10.0.0.11:60148/
[rospy.internal][INFO] 2016-01-26 09:02:34,077: topic[/watchdog_clear/tablet] removing connection to http://10.0.0.4:58821/
[rospy.impl.masterslave][INFO] 2016-01-26 09:02:34,077: Interaction exited
[rosout][INFO] 2016-01-26 09:02:34,193: Stopped
[rospy.core][INFO] 2016-01-26 09:02:34,193: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-26 09:12:26,958: init_node, name[/activity_manager], pid[31798]
[xmlrpc][INFO] 2016-01-26 09:12:26,975: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-01-26 09:12:26,976: Started XML-RPC server [http://10.0.0.11:50989/]
[rospy.impl.masterslave][INFO] 2016-01-26 09:12:26,976: _ready: http://10.0.0.11:50989/
[rospy.init][INFO] 2016-01-26 09:12:26,976: ROS Slave URI: [http://10.0.0.11:50989/]
[rospy.registration][INFO] 2016-01-26 09:12:26,976: Registering with master node http://10.0.0.11:11311/
[xmlrpc][INFO] 2016-01-26 09:12:26,976: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2016-01-26 09:12:27,076: registered with master
[rospy.rosout][INFO] 2016-01-26 09:12:27,077: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-26 09:12:27,078: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-26 09:12:27,080: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2016-01-26 09:12:27,126: Starting new timer
[rosout][INFO] 2016-01-26 09:12:27,126: Waiting for display manager services to become available
[rospy.internal][INFO] 2016-01-26 09:12:27,142: topic[/activity] adding connection to [http://10.0.0.11:50989/], count 0
[rospy.internal][INFO] 2016-01-26 09:12:27,145: topic[/activity] adding connection to [/activity_manager], count 0
[rospy.internal][INFO] 2016-01-26 09:12:27,172: topic[/watchdog_clear/tablet] adding connection to [http://10.0.0.4:38206/], count 0
[rospy.internal][INFO] 2016-01-26 09:12:27,173: topic[/activity] adding connection to [/log], count 1
[rospy.internal][INFO] 2016-01-26 09:12:27,325: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-26 09:12:28,103: topic[/activity] adding connection to [/learning_words_nao], count 2
[rospy.internal][INFO] 2016-01-26 09:12:28,478: topic[/activity] adding connection to [/drawing_nao], count 3
[rospy.internal][INFO] 2016-01-26 09:12:28,509: topic[/activity] adding connection to [http://10.0.0.11:44182/], count 1
[rosout][INFO] 2016-01-26 09:12:29,127: Nao configuration: writing=True, speaking=True (english), standing=False, handedness=right
[rosout][INFO] 2016-01-26 09:12:33,093: STATE: waiting_for_robot_to_connect
[rosout][INFO] 2016-01-26 09:12:33,593: STATE: STARTING_INTERACTION
[rosout][INFO] 2016-01-26 09:12:35,368: NAO: Hello. I'm Clem.
[rosout][INFO] 2016-01-26 09:12:36,870: STATE: ACTIVITY
[rosout][INFO] 2016-01-26 09:12:58,878: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:13:01,358: Re-connection
[rosout][INFO] 2016-01-26 09:14:02,652: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:14:05,136: Re-connection
[rosout][INFO] 2016-01-26 09:14:46,871: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:14:49,368: Re-connection
[rosout][INFO] 2016-01-26 09:15:24,911: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:15:27,267: Re-connection
[rosout][INFO] 2016-01-26 09:16:15,148: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:16:17,433: Re-connection
[rosout][INFO] 2016-01-26 09:17:06,955: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:17:09,407: Re-connection
[rosout][INFO] 2016-01-26 09:17:48,987: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:17:51,369: Re-connection
[rosout][INFO] 2016-01-26 09:18:34,707: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:18:37,129: Re-connection
[rosout][INFO] 2016-01-26 09:19:22,764: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:19:25,047: Re-connection
[rosout][INFO] 2016-01-26 09:20:24,669: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:20:27,068: Re-connection
[rosout][INFO] 2016-01-26 09:21:15,518: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:21:17,983: Re-connection
[rosout][INFO] 2016-01-26 09:22:03,550: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:22:05,945: Re-connection
[rosout][INFO] 2016-01-26 09:22:43,167: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:22:45,529: Re-connection
[rospy.internal][INFO] 2016-01-26 09:23:01,514: topic[/stop_learning] adding connection to [http://10.0.0.11:35988/], count 0
[rosout][INFO] 2016-01-26 09:23:02,279: STATE: STOPPING
[rospy.internal][ERROR] 2016-01-26 09:23:02,315: Unable to initiate TCP/IP socket to 10.0.0.11:59623 (http://10.0.0.11:44182/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rosout][WARNING] 2016-01-26 09:23:03,001: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2016-01-26 09:23:03,002: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 321, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 365, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][WARNING] 2016-01-26 09:23:03,317: Unknown error initiating TCP/IP socket to 10.0.0.11:59623 (http://10.0.0.11:44182/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-26 09:23:03,317: topic[/activity] removing connection to http://10.0.0.11:44182/
[rospy.internal][ERROR] 2016-01-26 09:23:04,396: Unable to initiate TCP/IP socket to 10.0.0.11:49091 (http://10.0.0.11:35988/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-26 09:23:05,396: Unknown error initiating TCP/IP socket to 10.0.0.11:49091 (http://10.0.0.11:35988/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-26 09:23:05,397: topic[/stop_learning] removing connection to http://10.0.0.11:35988/
[rospy.core][INFO] 2016-01-26 09:23:06,438: signal_shutdown [Interaction exited]
[rospy.internal][INFO] 2016-01-26 09:23:06,443: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-26 09:23:06,443: topic[/activity] removing connection to /activity_manager
[rospy.internal][INFO] 2016-01-26 09:23:06,468: topic[/activity] removing connection to /log
[rospy.internal][INFO] 2016-01-26 09:23:06,469: topic[/activity] removing connection to /learning_words_nao
[rospy.internal][INFO] 2016-01-26 09:23:06,469: topic[/activity] removing connection to /drawing_nao
[rospy.internal][WARNING] 2016-01-26 09:23:06,469: Unknown error initiating TCP/IP socket to 10.0.0.11:34347 (http://10.0.0.11:50989/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 556, in connect
    self.write_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 607, in write_header
    self.stat_bytes += write_ros_handshake_header(sock, protocol.get_header_fields())
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 419, in write_ros_handshake_header
    sock.sendall(s)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 32] Broken pipe

[rospy.internal][INFO] 2016-01-26 09:23:06,469: topic[/activity] removing connection to http://10.0.0.11:50989/
[rospy.internal][INFO] 2016-01-26 09:23:06,472: topic[/activity] removing connection to http://10.0.0.11:50989/
[rospy.topics][ERROR] 2016-01-26 09:23:06,472: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 307, in close
    c.close()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 807, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2016-01-26 09:23:06,473: topic[/watchdog_clear/tablet] removing connection to http://10.0.0.4:38206/
[rospy.impl.masterslave][INFO] 2016-01-26 09:23:06,473: Interaction exited
[rospy.internal][WARNING] 2016-01-26 09:23:06,476: Unknown error initiating TCP/IP socket to 10.0.0.4:55074 (http://10.0.0.4:38206/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rosout][INFO] 2016-01-26 09:23:06,873: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:23:07,127: Stopped
[rospy.core][INFO] 2016-01-26 09:23:07,128: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-26 09:29:03,596: init_node, name[/activity_manager], pid[21664]
[xmlrpc][INFO] 2016-01-26 09:29:03,596: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-26 09:29:03,597: ROS Slave URI: [http://10.0.0.11:53599/]
[xmlrpc][INFO] 2016-01-26 09:29:03,597: Started XML-RPC server [http://10.0.0.11:53599/]
[rospy.impl.masterslave][INFO] 2016-01-26 09:29:03,597: _ready: http://10.0.0.11:53599/
[xmlrpc][INFO] 2016-01-26 09:29:03,597: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-26 09:29:03,598: Registering with master node http://10.0.0.11:11311/
[rospy.init][INFO] 2016-01-26 09:29:03,697: registered with master
[rospy.rosout][INFO] 2016-01-26 09:29:03,698: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-26 09:29:03,700: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-26 09:29:03,703: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2016-01-26 09:29:03,745: Starting new timer
[rosout][INFO] 2016-01-26 09:29:03,747: Waiting for display manager services to become available
[rospy.internal][INFO] 2016-01-26 09:29:03,753: topic[/activity] adding connection to [/log], count 0
[rospy.internal][INFO] 2016-01-26 09:29:03,770: topic[/activity] adding connection to [http://10.0.0.11:53599/], count 0
[rospy.internal][INFO] 2016-01-26 09:29:03,772: topic[/activity] adding connection to [/activity_manager], count 1
[rospy.internal][INFO] 2016-01-26 09:29:03,798: topic[/watchdog_clear/tablet] adding connection to [http://10.0.0.4:38206/], count 0
[rospy.internal][INFO] 2016-01-26 09:29:03,958: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-26 09:29:04,411: topic[/activity] adding connection to [/drawing_nao], count 2
[rospy.internal][INFO] 2016-01-26 09:29:04,495: topic[/activity] adding connection to [http://10.0.0.11:44918/], count 1
[rospy.internal][INFO] 2016-01-26 09:29:04,570: topic[/activity] adding connection to [/learning_words_nao], count 3
[rosout][INFO] 2016-01-26 09:29:05,749: Nao configuration: writing=True, speaking=True (english), standing=False, handedness=right
[rosout][INFO] 2016-01-26 09:29:09,401: STATE: waiting_for_robot_to_connect
[rosout][INFO] 2016-01-26 09:29:09,902: STATE: STARTING_INTERACTION
[rosout][INFO] 2016-01-26 09:29:11,868: NAO: Hello. I'm Clem.
[rosout][INFO] 2016-01-26 09:29:13,371: STATE: ACTIVITY
[rosout][INFO] 2016-01-26 09:29:28,168: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:29:30,629: Re-connection
[rosout][INFO] 2016-01-26 09:30:39,882: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:30:42,386: Re-connection
[rosout][INFO] 2016-01-26 09:31:56,772: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:31:58,645: Re-connection
[rosout][INFO] 2016-01-26 09:32:43,829: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:32:46,230: Re-connection
[rosout][INFO] 2016-01-26 09:33:24,752: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:33:27,059: Re-connection
[rosout][INFO] 2016-01-26 09:34:15,862: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:34:18,094: Re-connection
[rosout][INFO] 2016-01-26 09:35:00,791: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:35:03,148: Re-connection
[rosout][INFO] 2016-01-26 09:36:22,588: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:36:25,062: Re-connection
[rosout][INFO] 2016-01-26 09:37:17,043: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:37:19,347: Re-connection
[rosout][INFO] 2016-01-26 09:38:30,089: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:38:32,569: Re-connection
[rosout][INFO] 2016-01-26 09:39:25,370: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:39:27,828: Re-connection
[rosout][INFO] 2016-01-26 09:40:05,083: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:40:07,587: Re-connection
[rospy.internal][INFO] 2016-01-26 09:40:55,516: topic[/stop_learning] adding connection to [http://10.0.0.11:46316/], count 0
[rosout][INFO] 2016-01-26 09:40:56,248: STATE: STOPPING
[rospy.internal][ERROR] 2016-01-26 09:40:56,353: Unable to initiate TCP/IP socket to 10.0.0.11:47852 (http://10.0.0.11:44918/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2016-01-26 09:40:56,354: topic[/activity] adding connection to [/drawing_nao], count 4
[rospy.internal][INFO] 2016-01-26 09:40:56,354: topic[/activity] removing connection to /drawing_nao
[rospy.internal][WARNING] 2016-01-26 09:40:57,355: Unknown error initiating TCP/IP socket to 10.0.0.11:47852 (http://10.0.0.11:44918/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-26 09:40:57,355: topic[/activity] removing connection to http://10.0.0.11:44918/
[rospy.internal][WARNING] 2016-01-26 09:40:58,433: Unknown error initiating TCP/IP socket to 10.0.0.11:46757 (http://10.0.0.11:46316/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-26 09:40:58,433: topic[/stop_learning] removing connection to http://10.0.0.11:46316/
[rospy.core][INFO] 2016-01-26 09:41:00,443: signal_shutdown [Interaction exited]
[rospy.internal][INFO] 2016-01-26 09:41:00,450: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-26 09:41:00,450: topic[/activity] removing connection to /log
[rospy.internal][INFO] 2016-01-26 09:41:00,450: topic[/activity] removing connection to /activity_manager
[rospy.internal][ERROR] 2016-01-26 09:41:00,451: Unable to initiate TCP/IP socket to 10.0.0.11:53394 (http://10.0.0.11:53599/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2016-01-26 09:41:00,451: topic[/activity] removing connection to /learning_words_nao
[rospy.internal][INFO] 2016-01-26 09:41:00,452: topic[/activity] removing connection to /drawing_nao
[rospy.internal][INFO] 2016-01-26 09:41:00,452: topic[/activity] removing connection to http://10.0.0.11:53599/
[rospy.internal][INFO] 2016-01-26 09:41:00,452: topic[/watchdog_clear/tablet] removing connection to http://10.0.0.4:38206/
[rospy.impl.masterslave][INFO] 2016-01-26 09:41:00,455: Interaction exited
[rosout][INFO] 2016-01-26 09:41:00,794: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 09:41:01,081: Stopped
[rospy.core][INFO] 2016-01-26 09:41:01,082: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-26 10:24:04,193: init_node, name[/activity_manager], pid[13631]
[xmlrpc][INFO] 2016-01-26 10:24:04,195: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-26 10:24:04,196: ROS Slave URI: [http://10.0.0.11:52588/]
[xmlrpc][INFO] 2016-01-26 10:24:04,196: Started XML-RPC server [http://10.0.0.11:52588/]
[rospy.impl.masterslave][INFO] 2016-01-26 10:24:04,196: _ready: http://10.0.0.11:52588/
[xmlrpc][INFO] 2016-01-26 10:24:04,220: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-26 10:24:04,220: Registering with master node http://10.0.0.11:11311/
[rospy.init][INFO] 2016-01-26 10:24:04,296: registered with master
[rospy.rosout][INFO] 2016-01-26 10:24:04,296: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-26 10:24:04,304: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-26 10:24:04,318: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2016-01-26 10:24:04,356: Starting new timer
[rosout][INFO] 2016-01-26 10:24:04,357: Waiting for display manager services to become available
[rospy.internal][INFO] 2016-01-26 10:24:04,389: topic[/activity] adding connection to [http://10.0.0.11:52588/], count 0
[rospy.internal][INFO] 2016-01-26 10:24:04,391: topic[/activity] adding connection to [/activity_manager], count 0
[rospy.internal][INFO] 2016-01-26 10:24:04,460: topic[/watchdog_clear/tablet] adding connection to [http://10.0.0.4:55992/], count 0
[rospy.internal][INFO] 2016-01-26 10:24:04,471: topic[/activity] adding connection to [/log], count 1
[rospy.internal][INFO] 2016-01-26 10:24:04,530: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-26 10:24:05,227: topic[/activity] adding connection to [/drawing_nao], count 2
[rospy.internal][INFO] 2016-01-26 10:24:05,254: topic[/activity] adding connection to [http://10.0.0.11:33345/], count 1
[rospy.internal][INFO] 2016-01-26 10:24:05,327: topic[/activity] adding connection to [/learning_words_nao], count 3
[rosout][INFO] 2016-01-26 10:24:06,359: Nao configuration: writing=True, speaking=True (english), standing=False, handedness=right
[rosout][INFO] 2016-01-26 10:24:06,820: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:24:06,820: Re-connection
[rosout][INFO] 2016-01-26 10:24:09,376: STATE: waiting_for_robot_to_connect
[rosout][INFO] 2016-01-26 10:24:09,877: STATE: STARTING_INTERACTION
[rosout][INFO] 2016-01-26 10:24:11,714: NAO: Hello. I'm Clem.
[rosout][INFO] 2016-01-26 10:24:13,217: STATE: ACTIVITY
[rosout][INFO] 2016-01-26 10:24:26,039: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:24:28,331: Re-connection
[rosout][INFO] 2016-01-26 10:25:32,620: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:25:35,076: Re-connection
[rosout][INFO] 2016-01-26 10:25:43,589: Haven't received a clear on 'watchdog_clear/tablet' topic
[rospy.internal][WARNING] 2016-01-26 10:25:51,623: Unknown error initiating TCP/IP socket to 10.0.0.4:48552 (http://10.0.0.4:55992/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-26 10:25:51,623: topic[/watchdog_clear/tablet] removing connection to http://10.0.0.4:55992/
[rospy.internal][INFO] 2016-01-26 10:25:58,980: topic[/watchdog_clear/tablet] adding connection to [http://10.0.0.4:36090/], count 0
[rosout][INFO] 2016-01-26 10:25:59,021: Re-connection
[rosout][INFO] 2016-01-26 10:26:11,008: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:26:13,155: Re-connection
[rosout][INFO] 2016-01-26 10:26:58,823: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:27:01,217: Re-connection
[rosout][INFO] 2016-01-26 10:27:56,141: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:27:58,547: Re-connection
[rosout][INFO] 2016-01-26 10:28:33,159: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:28:35,624: Re-connection
[rosout][INFO] 2016-01-26 10:29:13,433: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:29:15,828: Re-connection
[rosout][INFO] 2016-01-26 10:29:47,430: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:29:49,827: Re-connection
[rosout][INFO] 2016-01-26 10:30:16,778: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:30:19,068: Re-connection
[rosout][INFO] 2016-01-26 10:30:41,385: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:30:43,777: Re-connection
[rosout][INFO] 2016-01-26 10:31:10,564: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:31:13,011: Re-connection
[rosout][INFO] 2016-01-26 10:31:45,765: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:31:48,257: Re-connection
[rosout][INFO] 2016-01-26 10:32:39,070: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:32:41,374: Re-connection
[rosout][INFO] 2016-01-26 10:33:44,548: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:33:44,564: Re-connection
[rosout][INFO] 2016-01-26 10:33:49,663: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:33:51,988: Re-connection
[rosout][INFO] 2016-01-26 10:35:00,195: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:35:02,307: Re-connection
[rosout][INFO] 2016-01-26 10:35:35,495: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:35:37,767: Re-connection
[rosout][INFO] 2016-01-26 10:36:23,668: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:36:25,828: Re-connection
[rosout][INFO] 2016-01-26 10:37:14,908: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:37:17,270: Re-connection
[rosout][INFO] 2016-01-26 10:37:43,596: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:37:45,851: Re-connection
[rosout][INFO] 2016-01-26 10:38:38,569: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:38:40,960: Re-connection
[rospy.internal][INFO] 2016-01-26 10:38:46,917: topic[/stop_learning] adding connection to [http://10.0.0.11:35210/], count 0
[rospy.internal][ERROR] 2016-01-26 10:38:47,756: Unable to initiate TCP/IP socket to 10.0.0.11:57199 (http://10.0.0.11:33345/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rosout][INFO] 2016-01-26 10:38:48,489: STATE: STOPPING
[rospy.internal][WARNING] 2016-01-26 10:38:48,758: Unknown error initiating TCP/IP socket to 10.0.0.11:57199 (http://10.0.0.11:33345/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-26 10:38:48,758: topic[/activity] removing connection to http://10.0.0.11:33345/
[rospy.internal][ERROR] 2016-01-26 10:38:49,930: Unable to initiate TCP/IP socket to 10.0.0.11:59230 (http://10.0.0.11:35210/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-26 10:38:50,931: Unknown error initiating TCP/IP socket to 10.0.0.11:59230 (http://10.0.0.11:35210/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-26 10:38:50,932: topic[/stop_learning] removing connection to http://10.0.0.11:35210/
[rospy.core][INFO] 2016-01-26 10:38:52,564: signal_shutdown [Interaction exited]
[rospy.internal][INFO] 2016-01-26 10:38:52,570: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-26 10:38:52,570: topic[/activity] removing connection to /activity_manager
[rospy.internal][INFO] 2016-01-26 10:38:52,570: topic[/activity] removing connection to /log
[rospy.internal][INFO] 2016-01-26 10:38:52,571: topic[/activity] removing connection to /drawing_nao
[rospy.internal][ERROR] 2016-01-26 10:38:52,571: Unable to initiate TCP/IP socket to 10.0.0.11:41672 (http://10.0.0.11:52588/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2016-01-26 10:38:52,571: topic[/activity] removing connection to /learning_words_nao
[rospy.internal][INFO] 2016-01-26 10:38:52,572: topic[/activity] removing connection to http://10.0.0.11:52588/
[rospy.internal][INFO] 2016-01-26 10:38:52,572: topic[/watchdog_clear/tablet] removing connection to http://10.0.0.4:36090/
[rospy.impl.masterslave][INFO] 2016-01-26 10:38:52,572: Interaction exited
[rosout][INFO] 2016-01-26 10:38:52,966: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:38:53,248: Stopped
[rospy.core][INFO] 2016-01-26 10:38:53,248: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-26 10:48:42,845: init_node, name[/activity_manager], pid[9992]
[xmlrpc][INFO] 2016-01-26 10:48:42,846: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-01-26 10:48:42,846: Started XML-RPC server [http://10.0.0.11:56965/]
[rospy.init][INFO] 2016-01-26 10:48:42,846: ROS Slave URI: [http://10.0.0.11:56965/]
[rospy.impl.masterslave][INFO] 2016-01-26 10:48:42,846: _ready: http://10.0.0.11:56965/
[xmlrpc][INFO] 2016-01-26 10:48:42,847: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-26 10:48:42,847: Registering with master node http://10.0.0.11:11311/
[rospy.init][INFO] 2016-01-26 10:48:42,947: registered with master
[rospy.rosout][INFO] 2016-01-26 10:48:42,947: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-26 10:48:42,948: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-26 10:48:42,949: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2016-01-26 10:48:42,961: Starting new timer
[rosout][INFO] 2016-01-26 10:48:42,962: Waiting for display manager services to become available
[rospy.internal][INFO] 2016-01-26 10:48:42,973: topic[/activity] adding connection to [http://10.0.0.11:56965/], count 0
[rospy.internal][INFO] 2016-01-26 10:48:42,975: topic[/activity] adding connection to [/activity_manager], count 0
[rospy.internal][INFO] 2016-01-26 10:48:43,016: topic[/watchdog_clear/tablet] adding connection to [http://10.0.0.4:36090/], count 0
[rospy.internal][INFO] 2016-01-26 10:48:43,054: topic[/activity] adding connection to [/log], count 1
[rospy.internal][INFO] 2016-01-26 10:48:43,221: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-26 10:48:43,579: topic[/activity] adding connection to [/learning_words_nao], count 2
[rospy.internal][INFO] 2016-01-26 10:48:43,653: topic[/activity] adding connection to [/drawing_nao], count 3
[rospy.internal][INFO] 2016-01-26 10:48:43,689: topic[/activity] adding connection to [http://10.0.0.11:39600/], count 1
[rosout][INFO] 2016-01-26 10:48:44,963: Nao configuration: writing=True, speaking=True (english), standing=False, handedness=right
[rosout][INFO] 2016-01-26 10:48:46,011: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:48:46,014: Re-connection
[rospy.core][INFO] 2016-01-26 10:48:49,341: signal_shutdown [atexit]
[rospy.internal][INFO] 2016-01-26 10:48:49,355: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-26 10:48:49,355: topic[/activity] removing connection to /activity_manager
[rospy.internal][INFO] 2016-01-26 10:48:49,356: topic[/activity] removing connection to /log
[rospy.internal][INFO] 2016-01-26 10:48:49,356: topic[/activity] removing connection to /learning_words_nao
[rospy.internal][INFO] 2016-01-26 10:48:49,357: topic[/activity] removing connection to /drawing_nao
[rospy.internal][INFO] 2016-01-26 10:48:49,357: topic[/activity] removing connection to http://10.0.0.11:56965/
[rospy.internal][INFO] 2016-01-26 10:48:49,359: topic[/activity] removing connection to http://10.0.0.11:39600/
[rospy.internal][INFO] 2016-01-26 10:48:49,359: topic[/watchdog_clear/tablet] removing connection to http://10.0.0.4:36090/
[rospy.internal][ERROR] 2016-01-26 10:48:49,359: Unable to initiate TCP/IP socket to 10.0.0.11:51741 (http://10.0.0.11:56965/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.impl.masterslave][INFO] 2016-01-26 10:48:49,360: atexit
[rospy.client][INFO] 2016-01-26 10:50:32,646: init_node, name[/activity_manager], pid[10882]
[xmlrpc][INFO] 2016-01-26 10:50:32,646: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-26 10:50:32,646: ROS Slave URI: [http://10.0.0.11:55881/]
[xmlrpc][INFO] 2016-01-26 10:50:32,646: Started XML-RPC server [http://10.0.0.11:55881/]
[rospy.impl.masterslave][INFO] 2016-01-26 10:50:32,647: _ready: http://10.0.0.11:55881/
[xmlrpc][INFO] 2016-01-26 10:50:32,647: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-26 10:50:32,647: Registering with master node http://10.0.0.11:11311/
[rospy.init][INFO] 2016-01-26 10:50:32,747: registered with master
[rospy.rosout][INFO] 2016-01-26 10:50:32,747: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-26 10:50:32,748: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-26 10:50:32,749: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2016-01-26 10:50:32,774: Starting new timer
[rosout][INFO] 2016-01-26 10:50:32,775: Waiting for display manager services to become available
[rospy.internal][INFO] 2016-01-26 10:50:32,819: topic[/activity] adding connection to [http://10.0.0.11:55881/], count 0
[rospy.internal][INFO] 2016-01-26 10:50:32,821: topic[/activity] adding connection to [/activity_manager], count 0
[rospy.internal][INFO] 2016-01-26 10:50:32,846: topic[/activity] adding connection to [/log], count 1
[rospy.internal][INFO] 2016-01-26 10:50:32,894: topic[/watchdog_clear/tablet] adding connection to [http://10.0.0.4:36090/], count 0
[rospy.internal][INFO] 2016-01-26 10:50:33,006: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-26 10:50:33,867: topic[/activity] adding connection to [/learning_words_nao], count 2
[rospy.internal][INFO] 2016-01-26 10:50:34,122: topic[/activity] adding connection to [/drawing_nao], count 3
[rospy.internal][INFO] 2016-01-26 10:50:34,182: topic[/activity] adding connection to [http://10.0.0.11:58336/], count 1
[rosout][INFO] 2016-01-26 10:50:34,776: Nao configuration: writing=True, speaking=True (english), standing=False, handedness=right
[rosout][INFO] 2016-01-26 10:50:39,730: STATE: waiting_for_robot_to_connect
[rosout][INFO] 2016-01-26 10:50:40,231: STATE: STARTING_INTERACTION
[rosout][INFO] 2016-01-26 10:50:41,982: NAO: Hello. I'm Clem.
[rosout][INFO] 2016-01-26 10:50:43,484: STATE: ACTIVITY
[rosout][INFO] 2016-01-26 10:51:12,301: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:51:14,759: Re-connection
[rosout][INFO] 2016-01-26 10:52:35,111: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:52:37,406: Re-connection
[rosout][INFO] 2016-01-26 10:53:28,278: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:53:30,644: Re-connection
[rosout][INFO] 2016-01-26 10:54:30,868: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:54:33,029: Re-connection
[rosout][INFO] 2016-01-26 10:55:10,103: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:55:12,541: Re-connection
[rosout][INFO] 2016-01-26 10:55:56,641: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:55:59,100: Re-connection
[rosout][INFO] 2016-01-26 10:56:41,770: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:56:44,278: Re-connection
[rosout][INFO] 2016-01-26 10:57:30,431: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:57:32,811: Re-connection
[rosout][INFO] 2016-01-26 10:58:18,234: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:58:20,548: Re-connection
[rosout][INFO] 2016-01-26 10:59:11,579: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 10:59:14,038: Re-connection
[rosout][INFO] 2016-01-26 11:00:04,842: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:00:07,285: Re-connection
[rosout][INFO] 2016-01-26 11:00:42,760: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:00:45,187: Re-connection
[rosout][INFO] 2016-01-26 11:01:24,584: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:01:27,054: Re-connection
[rospy.internal][INFO] 2016-01-26 11:01:55,283: topic[/stop_learning] adding connection to [http://10.0.0.11:39899/], count 0
[rospy.internal][ERROR] 2016-01-26 11:01:56,020: Unable to initiate TCP/IP socket to 10.0.0.11:43055 (http://10.0.0.11:58336/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rosout][INFO] 2016-01-26 11:01:56,333: STATE: STOPPING
[rospy.internal][WARNING] 2016-01-26 11:01:57,029: Unknown error initiating TCP/IP socket to 10.0.0.11:43055 (http://10.0.0.11:58336/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-26 11:01:57,029: topic[/activity] removing connection to http://10.0.0.11:58336/
[rospy.internal][ERROR] 2016-01-26 11:01:58,234: Unable to initiate TCP/IP socket to 10.0.0.11:53428 (http://10.0.0.11:39899/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-26 11:01:59,247: Unknown error initiating TCP/IP socket to 10.0.0.11:53428 (http://10.0.0.11:39899/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-26 11:01:59,248: topic[/stop_learning] removing connection to http://10.0.0.11:39899/
[rospy.core][INFO] 2016-01-26 11:02:00,410: signal_shutdown [Interaction exited]
[rospy.internal][INFO] 2016-01-26 11:02:00,416: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-26 11:02:00,417: topic[/activity] removing connection to /activity_manager
[rospy.internal][INFO] 2016-01-26 11:02:00,417: topic[/activity] removing connection to /log
[rospy.internal][INFO] 2016-01-26 11:02:00,417: topic[/activity] removing connection to /learning_words_nao
[rospy.internal][INFO] 2016-01-26 11:02:00,418: topic[/activity] removing connection to /drawing_nao
[rospy.internal][INFO] 2016-01-26 11:02:00,418: topic[/activity] removing connection to http://10.0.0.11:55881/
[rospy.internal][INFO] 2016-01-26 11:02:00,418: topic[/watchdog_clear/tablet] removing connection to http://10.0.0.4:36090/
[rospy.impl.masterslave][INFO] 2016-01-26 11:02:00,418: Interaction exited
[rospy.internal][ERROR] 2016-01-26 11:02:00,419: Unable to initiate TCP/IP socket to 10.0.0.11:60922 (http://10.0.0.11:55881/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rosout][INFO] 2016-01-26 11:02:00,567: Stopped
[rospy.core][INFO] 2016-01-26 11:02:00,568: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-26 11:12:10,274: init_node, name[/activity_manager], pid[1894]
[xmlrpc][INFO] 2016-01-26 11:12:10,275: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-26 11:12:10,275: ROS Slave URI: [http://10.0.0.11:55877/]
[xmlrpc][INFO] 2016-01-26 11:12:10,275: Started XML-RPC server [http://10.0.0.11:55877/]
[rospy.impl.masterslave][INFO] 2016-01-26 11:12:10,275: _ready: http://10.0.0.11:55877/
[rospy.registration][INFO] 2016-01-26 11:12:10,276: Registering with master node http://10.0.0.11:11311/
[xmlrpc][INFO] 2016-01-26 11:12:10,276: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2016-01-26 11:12:10,375: registered with master
[rospy.rosout][INFO] 2016-01-26 11:12:10,376: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-26 11:12:10,377: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-26 11:12:10,378: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2016-01-26 11:12:10,388: Starting new timer
[rosout][INFO] 2016-01-26 11:12:10,389: Waiting for display manager services to become available
[rospy.internal][INFO] 2016-01-26 11:12:10,391: topic[/activity] adding connection to [http://10.0.0.11:55877/], count 0
[rospy.internal][INFO] 2016-01-26 11:12:10,397: topic[/activity] adding connection to [/activity_manager], count 0
[rospy.internal][INFO] 2016-01-26 11:12:10,406: topic[/activity] adding connection to [/log], count 1
[rospy.internal][INFO] 2016-01-26 11:12:10,455: topic[/watchdog_clear/tablet] adding connection to [http://10.0.0.4:36090/], count 0
[rospy.internal][INFO] 2016-01-26 11:12:10,599: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-26 11:12:10,875: topic[/activity] adding connection to [/drawing_nao], count 2
[rospy.internal][INFO] 2016-01-26 11:12:10,923: topic[/activity] adding connection to [http://10.0.0.11:59395/], count 1
[rospy.internal][INFO] 2016-01-26 11:12:10,976: topic[/activity] adding connection to [/learning_words_nao], count 3
[rosout][INFO] 2016-01-26 11:12:12,391: Nao configuration: writing=True, speaking=True (english), standing=False, handedness=right
[rosout][INFO] 2016-01-26 11:12:15,213: STATE: waiting_for_robot_to_connect
[rosout][INFO] 2016-01-26 11:12:15,714: STATE: STARTING_INTERACTION
[rosout][INFO] 2016-01-26 11:12:17,349: NAO: Hello. I'm Clem.
[rosout][INFO] 2016-01-26 11:12:18,851: STATE: ACTIVITY
[rosout][INFO] 2016-01-26 11:12:31,540: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:12:34,011: Re-connection
[rosout][INFO] 2016-01-26 11:13:34,929: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:13:37,386: Re-connection
[rosout][INFO] 2016-01-26 11:14:25,393: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:14:27,858: Re-connection
[rosout][INFO] 2016-01-26 11:15:16,069: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:15:18,493: Re-connection
[rosout][INFO] 2016-01-26 11:15:55,511: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:15:57,935: Re-connection
[rosout][INFO] 2016-01-26 11:16:37,540: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:16:39,996: Re-connection
[rosout][INFO] 2016-01-26 11:17:37,753: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:17:40,189: Re-connection
[rosout][INFO] 2016-01-26 11:18:14,432: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:18:16,917: Re-connection
[rosout][INFO] 2016-01-26 11:18:56,952: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:18:59,444: Re-connection
[rosout][INFO] 2016-01-26 11:19:34,054: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:19:36,508: Re-connection
[rosout][INFO] 2016-01-26 11:20:08,063: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:20:10,419: Re-connection
[rosout][INFO] 2016-01-26 11:20:37,468: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:20:39,929: Re-connection
[rosout][INFO] 2016-01-26 11:21:11,764: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:21:14,179: Re-connection
[rosout][INFO] 2016-01-26 11:21:45,564: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:21:48,010: Re-connection
[rosout][INFO] 2016-01-26 11:22:20,751: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:22:23,188: Re-connection
[rospy.internal][INFO] 2016-01-26 11:22:45,817: topic[/stop_learning] adding connection to [http://10.0.0.11:38713/], count 0
[rosout][INFO] 2016-01-26 11:22:46,489: STATE: STOPPING
[rospy.internal][ERROR] 2016-01-26 11:22:46,600: Unable to initiate TCP/IP socket to 10.0.0.11:37958 (http://10.0.0.11:59395/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-26 11:22:47,608: Unknown error initiating TCP/IP socket to 10.0.0.11:37958 (http://10.0.0.11:59395/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-26 11:22:47,608: topic[/activity] removing connection to http://10.0.0.11:59395/
[rospy.internal][WARNING] 2016-01-26 11:22:48,831: Unknown error initiating TCP/IP socket to 10.0.0.11:41884 (http://10.0.0.11:38713/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 363, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2016-01-26 11:22:48,831: topic[/stop_learning] removing connection to http://10.0.0.11:38713/
[rospy.core][INFO] 2016-01-26 11:22:50,629: signal_shutdown [Interaction exited]
[rospy.internal][INFO] 2016-01-26 11:22:50,635: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-26 11:22:50,635: topic[/activity] removing connection to /activity_manager
[rospy.internal][INFO] 2016-01-26 11:22:50,636: topic[/activity] removing connection to /log
[rospy.internal][INFO] 2016-01-26 11:22:50,636: topic[/activity] removing connection to /drawing_nao
[rospy.internal][INFO] 2016-01-26 11:22:50,636: topic[/activity] removing connection to /learning_words_nao
[rospy.internal][ERROR] 2016-01-26 11:22:50,637: Unable to initiate TCP/IP socket to 10.0.0.11:56772 (http://10.0.0.11:55877/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2016-01-26 11:22:50,637: topic[/activity] removing connection to http://10.0.0.11:55877/
[rospy.internal][INFO] 2016-01-26 11:22:50,637: topic[/watchdog_clear/tablet] removing connection to http://10.0.0.4:36090/
[rospy.impl.masterslave][INFO] 2016-01-26 11:22:50,637: Interaction exited
[rosout][INFO] 2016-01-26 11:22:50,807: Stopped
[rospy.core][INFO] 2016-01-26 11:22:50,808: signal_shutdown [atexit]
[rospy.client][INFO] 2016-01-26 11:32:49,443: init_node, name[/activity_manager], pid[23896]
[xmlrpc][INFO] 2016-01-26 11:32:49,443: XML-RPC server binding to 0.0.0.0:0
[rospy.init][INFO] 2016-01-26 11:32:49,444: ROS Slave URI: [http://10.0.0.11:45328/]
[xmlrpc][INFO] 2016-01-26 11:32:49,444: Started XML-RPC server [http://10.0.0.11:45328/]
[rospy.impl.masterslave][INFO] 2016-01-26 11:32:49,444: _ready: http://10.0.0.11:45328/
[xmlrpc][INFO] 2016-01-26 11:32:49,444: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2016-01-26 11:32:49,444: Registering with master node http://10.0.0.11:11311/
[rospy.init][INFO] 2016-01-26 11:32:49,544: registered with master
[rospy.rosout][INFO] 2016-01-26 11:32:49,544: initializing /rosout core topic
[rospy.rosout][INFO] 2016-01-26 11:32:49,547: connected to core topic /rosout
[rospy.simtime][INFO] 2016-01-26 11:32:49,548: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2016-01-26 11:32:49,578: Starting new timer
[rosout][INFO] 2016-01-26 11:32:49,580: Waiting for display manager services to become available
[rospy.internal][INFO] 2016-01-26 11:32:49,604: topic[/activity] adding connection to [/log], count 0
[rospy.internal][INFO] 2016-01-26 11:32:49,611: topic[/activity] adding connection to [http://10.0.0.11:45328/], count 0
[rospy.internal][INFO] 2016-01-26 11:32:49,613: topic[/activity] adding connection to [/activity_manager], count 1
[rospy.internal][INFO] 2016-01-26 11:32:49,646: topic[/watchdog_clear/tablet] adding connection to [http://10.0.0.4:36090/], count 0
[rospy.internal][INFO] 2016-01-26 11:32:49,672: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2016-01-26 11:32:49,674: topic[/activity] adding connection to [/drawing_nao], count 2
[rospy.internal][INFO] 2016-01-26 11:32:49,731: topic[/activity] adding connection to [http://10.0.0.11:42617/], count 1
[rospy.internal][INFO] 2016-01-26 11:32:50,082: topic[/activity] adding connection to [/learning_words_nao], count 3
[rosout][INFO] 2016-01-26 11:32:51,582: Nao configuration: writing=True, speaking=True (english), standing=False, handedness=right
[rosout][INFO] 2016-01-26 11:32:55,236: STATE: waiting_for_robot_to_connect
[rosout][INFO] 2016-01-26 11:32:55,737: STATE: STARTING_INTERACTION
[rosout][INFO] 2016-01-26 11:32:57,367: NAO: Hello. I'm Clem.
[rosout][INFO] 2016-01-26 11:32:58,869: STATE: ACTIVITY
[rosout][INFO] 2016-01-26 11:33:09,713: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:33:12,197: Re-connection
[rosout][INFO] 2016-01-26 11:34:02,978: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:34:05,437: Re-connection
[rosout][INFO] 2016-01-26 11:34:34,084: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:34:36,517: Re-connection
[rosout][INFO] 2016-01-26 11:36:17,268: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:36:19,661: Re-connection
[rosout][INFO] 2016-01-26 11:36:49,282: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:36:51,527: Re-connection
[rosout][INFO] 2016-01-26 11:38:08,203: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:38:10,349: Re-connection
[rosout][INFO] 2016-01-26 11:38:34,878: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:38:37,356: Re-connection
[rosout][INFO] 2016-01-26 11:39:34,967: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:39:37,220: Re-connection
[rosout][INFO] 2016-01-26 11:41:10,966: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:41:13,408: Re-connection
[rosout][INFO] 2016-01-26 11:42:09,675: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:42:11,936: Re-connection
[rosout][INFO] 2016-01-26 11:43:39,552: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:43:41,829: Re-connection
[rospy.internal][INFO] 2016-01-26 11:44:26,652: topic[/stop_learning] adding connection to [http://10.0.0.11:47628/], count 0
[rospy.internal][ERROR] 2016-01-26 11:44:27,530: Unable to initiate TCP/IP socket to 10.0.0.11:41256 (http://10.0.0.11:42617/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2016-01-26 11:44:27,534: topic[/activity] adding connection to [/drawing_nao], count 4
[rospy.internal][INFO] 2016-01-26 11:44:27,535: topic[/activity] removing connection to /drawing_nao
[rospy.internal][WARNING] 2016-01-26 11:44:28,531: Unknown error initiating TCP/IP socket to 10.0.0.11:41256 (http://10.0.0.11:42617/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-26 11:44:28,532: topic[/activity] removing connection to http://10.0.0.11:42617/
[rosout][INFO] 2016-01-26 11:44:28,608: STATE: STOPPING
[rospy.internal][ERROR] 2016-01-26 11:44:29,673: Unable to initiate TCP/IP socket to 10.0.0.11:48166 (http://10.0.0.11:47628/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 580, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2016-01-26 11:44:30,688: Unknown error initiating TCP/IP socket to 10.0.0.11:48166 (http://10.0.0.11:47628/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2016-01-26 11:44:30,688: topic[/stop_learning] removing connection to http://10.0.0.11:47628/
[rospy.core][INFO] 2016-01-26 11:44:32,708: signal_shutdown [Interaction exited]
[rospy.internal][INFO] 2016-01-26 11:44:32,718: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-01-26 11:44:32,718: topic[/activity] removing connection to /log
[rospy.internal][INFO] 2016-01-26 11:44:32,719: topic[/activity] removing connection to /activity_manager
[rospy.internal][INFO] 2016-01-26 11:44:32,719: topic[/activity] removing connection to /learning_words_nao
[rospy.internal][INFO] 2016-01-26 11:44:32,719: topic[/activity] removing connection to /drawing_nao
[rospy.internal][INFO] 2016-01-26 11:44:32,720: topic[/activity] removing connection to http://10.0.0.11:45328/
[rospy.internal][WARNING] 2016-01-26 11:44:32,720: Unknown error initiating TCP/IP socket to 10.0.0.11:43339 (http://10.0.0.11:45328/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2016-01-26 11:44:32,720: topic[/watchdog_clear/tablet] removing connection to http://10.0.0.4:36090/
[rospy.impl.masterslave][INFO] 2016-01-26 11:44:32,720: Interaction exited
[rospy.internal][WARNING] 2016-01-26 11:44:32,728: Unknown error initiating TCP/IP socket to 10.0.0.4:38616 (http://10.0.0.4:36090/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rosout][INFO] 2016-01-26 11:44:33,037: Haven't received a clear on 'watchdog_clear/tablet' topic
[rosout][INFO] 2016-01-26 11:44:33,368: Stopped
[rospy.core][INFO] 2016-01-26 11:44:33,369: signal_shutdown [atexit]
